paramiko/pkey.py: With Py3, don't decode private keys during _write_private_key() to string.
  A bytes object is needed for write operations with Python3.

  This resolves...

  ```
  File "pyhoca-gui.upstream/pyhoca-gui/x2go/backends/terminal/plain.py", line 936, in share_local_folder
    _auth_rsakey.write_private_key(_tmp_io_object)
  File "/usr/lib/python3/dist-packages/paramiko/rsakey.py", line 154, in write_private_key
    password=password,
  File "/usr/lib/python3/dist-packages/paramiko/pkey.py", line 367, in _write_private_key
    serialization.Encoding.PEM, format, encryption
  TypeError: a bytes-like object is required, not 'str'
  ```